[versions]
agp = "8.13.1"
kotlin = "2.3.21"
depAnalysis = "3.10.0"
appcompat = "1.7.1"

[libraries]
androidx-appcompatResources = { group = "androidx.appcompat", name = "appcompat-resources", version.ref = "appcompat" }

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
dependency-analysis = { id ="com.autonomousapps.dependency-analysis", version.ref = "depAnalysis"}

